# Introducción al Álgebra Lineal

El álgebra lineal es una rama de las matemáticas que se enfoca en el estudio de vectores, espacios vectoriales, transformaciones lineales y matrices, así como en las propiedades que surgen de estas estructuras. El álgebra lineal tiene aplicaciones en diversas áreas como las matemáticas aplicadas, física, ingeniería, economía, informática, etc. 

Muchos conceptos de programación están intrínsicamente ligados al álgebra lineal. Por ejemplo, comúnmente los datos se representan en vectores y matrices. En algunas ramas de las ciencias de la computación como *procesamiento de imágenes* y *aprendizaje automático* es esencial tener conocimiento de álgebra lineal, pues toda la teoría matemática de ambos campos está fundada sobre esta rama de las matemáticas.

En esta capítulo de curso, aprenderemos a llevar muchos conceptos del álgebra lineal a la programación (en Python específicamente).

Una matriz general está definida como:

$$A = 
\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1m} \\
a_{21} & a_{22} & \cdots & a_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nm} 
\end{bmatrix}
\in \mathbb{R}^{n \times m}$$

En Python no existe algún tipo de dato que represente a una matriz. Sin embargo, podemos crear una lista de listas como una matriz.

Representaremos las siguientes matrices en Python:

$$A = 
\begin{bmatrix}
3 & 5 & 2 & 7 \\
1 & 9 & 4 & 10 \\
6 & 11 & 8 & 12 
\end{bmatrix}$$

$$B = 
\begin{bmatrix}
4 & 10 \\
1 & 3 \\
5 & 11 \\
7 & 8  
\end{bmatrix}$$

In [10]:
A = [[3, 5, 2, 7], 
     [1, 9, 4, 10],
     [6, 11, 8, 12]]

A

[[3, 5, 2, 7], [1, 9, 4, 10], [6, 11, 8, 12]]

In [11]:
B = [[4, 10],
     [1, 3],
     [5, 11],
     [7, 8]]

B

[[4, 10], [1, 3], [5, 11], [7, 8]]

La multiplicación de una matriz $A \in \mathbb{R}^{n\times k}$ con otra matriz $B \in \mathbb{R}^{k\times m}$ da como resultado una matriz $C \in \mathbb{R}^{n\times m}$ donde sus entradas están definidas por:

$$
C_{ij} = \sum_{t=1}^{k} A_{it} \cdot B_{tj}
$$

Podemos implementar la multiplación de matrices en una función de Python:

In [18]:
def matrix_multiplication(A, B):
    n = len(A)
    k = len(A[0])
    m = len(B[0])

    C = [[0 for _ in range(m)] for _ in range(n)]

    for i in range(n):
        for j in range(m):
            for t in range(k):
                C[i][j] += A[i][t] * B[t][j]

    return C

In [20]:
C = matrix_multiplication(A, B)
C

[[76, 123], [103, 161], [159, 277]]

Y así podríamos empezar a implementar cada concepto del álgebra lineal en Python. Sin embargo, ya existe una librería muy poderosa que tiene implementada muchos conceptos de álgebra lineal. Además, todos estos algoritmos son muy sencillos de usar y eficientes.

NumPy es una librería de Python utilizada principalmente para realizar operaciones numéricas en matrices y arreglos multidimensionales de manera eficiente y rápida. Es una de las bibliotecas más populares y ampliamente utilizadas en el ecosistema de Python para computación científica y análisis de datos. Además, NumPy se utiliza comúnmente en conjunto con otras liberías de Python para análisis de datos y computación científica, como SciPy, Pandas y Matplotlib. 

In [21]:
import numpy as np

# Declaración de dos matrices A y B

A = np.array([[3, 5, 2, 7], 
              [1, 9, 4, 10],
              [6, 11, 8, 12]])

B = np.array([[4, 10],
              [1, 3],
              [5, 11],
              [7, 8]])

In [22]:
A

array([[ 3,  5,  2,  7],
       [ 1,  9,  4, 10],
       [ 6, 11,  8, 12]])

In [23]:
B

array([[ 4, 10],
       [ 1,  3],
       [ 5, 11],
       [ 7,  8]])

La multiplicación de matrices se puede realizar simplemente con el operador `@`:

In [24]:
C = A @ B
C

array([[ 76, 123],
       [103, 161],
       [159, 277]])

Y no solo la multiplicación de matrices, sino que muchas más funciones relacionadas al álgebra lineal están ya implementadas en la librería NumPy. 