# Vectores y Matrices

## Vectores

La clase `numpy.ndarray` es la clase principal en NumPy que representa arreglos multidimensionales homogéneos. Esta clase es la base sobre la cual se construyen muchas de las funcionalidades de la biblioteca NumPy. Para crear un objeto `numpy.ndarray` usaremos la función `numpy.array`:

In [31]:
# Es comun usar np como alias
import numpy as np

# Le pasamos como parámetro una lista de números
A = np.array([3, 5, 2, 8, 0, 1, 13])

In [33]:
# El tipo de A es numpy.ndarray

type(A)

numpy.ndarray

In [34]:
print(A)

[ 3  5  2  8  0  1 13]


Podemos consultar la dimensionalidad del arreglo con el atributo `shape`:

In [35]:
A.shape

(7,)

Vemos que el resultado obtenido es una tupla, donde solo hay un número y se encuentra vacío la segunda posición en la tupla. Esto da a entender que se trata de un vector, es decir, solo tiene una dimensión.

NumPy también tiene sus propios tipos de datos. Aquí puedes encontrar una referencia con todos los tipos: https://interactivechaos.com/es/manual/tutorial-de-numpy/tipos-de-datos.

Podemos consultar el tipo de dato de sus elementos con el parámetro `dtype`:

In [36]:
A.dtype

dtype('int64')

Podemos obtener un subconjunto del vector, funciona de manera similar al *slicing* de cadenas para obtener subcadenas:

In [37]:
print(A[0 : 4])

[3 5 2 8 0]


In [39]:
print(A[3 : 6])

[8 0 1]


In [41]:
print(A[2 : ])

[ 2  8  0  1 13]


In [42]:
print(A[ : 5])

[3 5 2 8 0]


## Matrices

Ahora declararemos un arreglo bidimensional, es decir una matriz. Para ello, en vez de pasar una lista como parámetro a `np.array`, le pasaremos una lista de listas.

In [26]:
M = np.array([[1, 2, 3],
                [-3, 4, 5]])

In [27]:
type(M)

numpy.ndarray

In [28]:
print(M)

[[ 1  2  3]
 [-3  4  5]]


In [29]:
M.shape

(2, 3)