# Módulo 'linalg' de NumPy

El módulo `numpy.linalg` provee varias funciones ya implementadas de álgebra lineal como: 
1. Producto punto y cruz de vectores
2. Suma, resta y multiplicación de vectores
3. Autovales de matrices
4. Solución de sistemas de ecuaciones lineales

Puedes encontrar una referencia completa de este módulo en la siguiente página: https://numpy.org/doc/stable/reference/routines.linalg.html.

## Operaciones básicas de matrices

Ya vimos en la introducción de este capítulo, las operaciones de matrices con NumPy son muy sencillas de aplicar y además eficientes. En esta sección, veremos algunas operaciones que podemos hacer con matrices en NumPy.

### Suma y resta de matrices

La suma de dos matrices $A$ y $B$ nos da como resultado una matriz $C$, tal que

$$
C_{ij} = A_{ij} + B_{ij}
$$

Y la resta de dos matrices $A$ y $B$:

$$
D_{ij} = A_{ij} - B_{ij}
$$

Implementación sin NumPy:

In [3]:
A = [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

B = [[-1, 10, 5, 4],
     [3, -12, 1, -2],
     [7, 9, 2, -5]]

n = 3
m = 4

In [6]:
# Suma de matrices

C = [[0 for _ in range(m)] for _ in range(n)]

for i in range(n):
    for j in range(m):
        C[i][j] = A[i][j] + B[i][j]

C

[[0, 12, 8, 8], [8, -6, 8, 6], [16, 19, 13, 7]]

In [5]:
# Resta de matrices

D = [[0 for _ in range(m)] for _ in range(n)]

for i in range(n):
    for j in range(m):
        D[i][j] = A[i][j] - B[i][j]

D

[[2, -8, -2, 0], [2, 18, 6, 10], [2, 1, 9, 17]]

Implementación con NumPy

In [7]:
import numpy as np

# Convertimos A a un np.ndarray
A = np.array(A)

# Lo mismo para B
B = np.array(B)



In [8]:
# Simplemente la suma de dos matrices, la obtenemos con el operador '+'
C = A + B

print(C)

[[ 0 12  8  8]
 [ 8 -6  8  6]
 [16 19 13  7]]


In [9]:
# Y para la resta, es similar, usaremos el operador '-'

D = A - B

print(D)

[[ 2 -8 -2  0]
 [ 2 18  6 10]
 [ 2  1  9 17]]


### Multiplicación de matrices

En la introducción del capítulo, ya vimos el caso de la multiplicación de matrices.

La multiplicación de una matriz $A \in \mathbb{R}^{n\times k}$ con otra matriz $B \in \mathbb{R}^{k\times m}$ da como resultado una matriz $C \in \mathbb{R}^{n\times m}$ donde sus entradas están definidas por:

$$
C_{ij} = \sum_{t=1}^{k} A_{it} \cdot B_{tj}
$$

Implementación sin NumPy:

In [11]:
A = [[3, 5, 2, 7], 
     [1, 9, 4, 10],
     [6, 11, 8, 12]]

B = [[4, 10],
     [1, 3],
     [5, 11],
     [7, 8]]

In [12]:
def matrix_multiplication(A, B):
    n = len(A)
    k = len(A[0])
    m = len(B[0])

    C = [[0 for _ in range(m)] for _ in range(n)]

    for i in range(n):
        for j in range(m):
            for t in range(k):
                C[i][j] += A[i][t] * B[t][j]

    return C

C = matrix_multiplication(A, B)
print(C)

[[76, 123], [103, 161], [159, 277]]


Implementación con NumPy:

In [15]:
# Convertimos las matrices a tipo np.ndarray

A = np.array(A)
B = np.array(B)

C = A @ B
C

array([[ 76, 123],
       [103, 161],
       [159, 277]])

Algo importante a resaltar de la multiplicación de matrices de NumPy, a parte de su simplicidad, es su eficiencia. Y cuando hablamos de **eficiencia**, nos referimos a que el tiempo de ejecución y los recursos necesarios están optimizados para ser los mínimos posibles. 

Comparemos el tiempo de ejecución entre ambos métodos. Para esto, multiplicaremos matrices de $5000 \times 5000$ de dimensión:

In [30]:
import random

n = 500

# Creamos dos matrices de n x n. Sus elementos son valores aleatorios entre 0 y 1

A = [[random.uniform(0, 1) for _ in range(n)] for _ in range(n)]
B = [[random.uniform(0, 1) for _ in range(n)] for _ in range(n)]

In [31]:
%%time

C = matrix_multiplication(A, B)

CPU times: user 7.3 s, sys: 5.76 ms, total: 7.3 s
Wall time: 7.32 s


In [32]:
A = np.array(A)
B = np.array(B)

In [33]:
%%time

C = A @ B

CPU times: user 35.4 ms, sys: 23.9 ms, total: 59.3 ms
Wall time: 8.3 ms


Comparando ambos tiempos de ejecución, podemos notar que la multiplicación con NumPy es considerablemente más rápida. 