# Determinante de una matriz

Calcular la determinante de una matriz es importante en varios contextos matemáticos y aplicaciones prácticas. Por ejemplo:

1. *Resolución de sistemas de ecuaciones lineales:* La determinante de una matriz es cero si y solo si la matriz es singular, lo que significa que no tiene inversa. Por lo tanto, al calcular la determinante de una matriz, podemos determinar si un sistema de ecuaciones lineales tiene una solución única, ninguna solución o infinitas soluciones.

2. *Cálculo de la inversa de una matriz:* La inversa de una matriz se puede calcular usando la determinante de una matriz.

3. *Optimización y álgebra lineal numérica:* En algoritmos de optimización y álgebra lineal numérica, la determinante de una matriz puede ser un indicador importante de la estabilidad numérica de los cálculos. Por ejemplo, en el cálculo de autovalores y autovectores, la determinante de la matriz es un factor relevante.

Para calcular la determinante de una matriz cuadrada (recordar que solo las matrices cuadradas tienen determinante), existen muchos métodos. Aquí puedes ver una [referencia](https://math.libretexts.org/Courses/Community_College_of_Denver/MAT_2562_Differential_Equations_with_Linear_Algebra/12%3A_Matrices_and_Determinants/12.08%3A_Basic_Techniques_of_Determinants).

Implementar un algoritmo para el cálculo de la determinante es muy complicada y probablemente no sea eficiente. Por suerte, NumPy cuenta con una implementación del cálculo de la determinante de una matriz:

In [3]:
import numpy as np

A = np.array([[1, 5, -3, 2, 11],
             [2, 10, 0, -1, 5],
             [4, -4, 7, 1, 0],
             [11, 5, 3, 2, -7],
             [10, 9, 1, 0, 2]])

print(A)

[[ 1  5 -3  2 11]
 [ 2 10  0 -1  5]
 [ 4 -4  7  1  0]
 [11  5  3  2 -7]
 [10  9  1  0  2]]


In [5]:
# Simplemente llamamos a la función np.linalg.det

A_det = np.linalg.det(A)
A_det

-17238.000000000025

# Inversa de una matriz

Dada una matriz cuadrada $A$ no singular (su determinante es distinto a 0), decimos que la matriz $B$ es la **inversa** de $A$ si y solo si

$$
AB = BA = I
$$

donde $I$ es la matriz identidad. ([Referencia](https://math.libretexts.org/Courses/Community_College_of_Denver/MAT_2562_Differential_Equations_with_Linear_Algebra/12%3A_Matrices_and_Determinants/12.08%3A_Basic_Techniques_of_Determinants)).

NumPy también tiene implementado el algoritmo para el cálculo de la inversa de una matriz:



In [10]:
A = np.array([[1, 5, -3, 2],
             [2, 10, 0, -1],
             [4, -4, 7, 1],
             [11, 5, 3, 2]])

In [11]:
A_inv = np.linalg.inv(A)
A_inv

array([[-0.12975207, -0.06446281, -0.12396694,  0.15950413],
       [ 0.07190083,  0.10578512,  0.04958678, -0.04380165],
       [ 0.04958678,  0.10743802,  0.20661157, -0.09917355],
       [ 0.45950413, -0.07107438,  0.24793388, -0.11900826]])

Ahora comprobaremos si la multiplicación entre $A$ y $A_{\text{inv}}$ nos resulta la matriz identidad

$$I_4 = 
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

In [12]:
print(A @ A_inv)

[[ 1.00000000e+00 -1.38777878e-16 -5.55111512e-17  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00 -2.77555756e-17  0.00000000e+00]
 [-5.55111512e-17  4.16333634e-17  1.00000000e+00 -4.16333634e-17]
 [ 3.33066907e-16  2.77555756e-17  0.00000000e+00  1.00000000e+00]]


Observamos que el resultado obtenido no es estrictamente igual a la matriz identidad. Podemos notar que la diagonal son efectivamente unos. Los demás números deberían ser igual a cero. Si nos fijamos en estos números, sus valores son prácticamente cero (`e-17` = $10^{-17}$). No llegan a ser cero exactamente debido a la precisión de NumPy. 

Obtenemos un resultado similar si multiplicamos de la siguiente manera:

In [13]:
print(A_inv @ A)

[[ 1.00000000e+00  2.49800181e-16  2.77555756e-17  5.55111512e-17]
 [-6.93889390e-17  1.00000000e+00 -6.93889390e-17  1.38777878e-17]
 [ 4.16333634e-17 -2.63677968e-16  1.00000000e+00 -2.77555756e-17]
 [-3.05311332e-16 -1.38777878e-16 -1.94289029e-16  1.00000000e+00]]
